name: Apaca HTML file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: File uploading....
        run: aws s3 cp index.html s3://s3cpibucket.github
